def profile():
    """The profile returned from ProxyCurl, saved to prevent token spending during tests"""

    return {
        "public_identifier": "bennie-robinson-48021331",
        "profile_pic_url": "https://media.licdn.com/dms/image/v2/C5603AQH4UTacFbYUOg/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1516469826903?e=1735776000&v=beta&t=O5QFAoScIp13akaaSp3wpK7Kwj-wfr7-XloSZxCOgSM",
        "background_cover_image_url": None,
        "first_name": "Bennie",
        "last_name": "Robinson",
        "full_name": "Bennie Robinson",
        "follower_count": 51,
        "occupation": "Graphic and Web Designer at KS Professional Computer Solutions",
        "headline": "Graphic and Web Designer at KS Professional Computer Solutions",
        "summary": "I have been learning HTML since the days of HTML 4.0, and have been excited in the constant flux and growth of the web. I went to school for Design, and have designed dozens of sites, freelance and through my current employer, KS Professional Computer Solutions. Please note that do not currently do freelance web sites. If you would like me to design a website for you, please contact my employer at (828) 355-5526.\n\nI believe in minimal, confident web design with attention to detail and structure, and hope to continue to refine my skill set to keep up with the pace of the web design community.\n\nSpecialties: HTML, CSS, jQuery, JavaScritpt, Photoshop, Illustrator, Photography.",
        "country": "US",
        "country_full_name": "United States",
        "city": "Boone",
        "state": "North Carolina",
        "experiences": [
            {
                "starts_at": {"day": 1, "month": 9, "year": 2011},
                "ends_at": None,
                "company": "KS Professional Computer Solutions",
                "company_linkedin_profile_url": None,
                "company_facebook_profile_url": None,
                "title": "Graphic and Web Designer",
                "description": "I design websites, advertisements, billboards. I code websites I design using HTML, CSS, JavaScript, and occasionally PHP and MySQL.",
                "location": "Boone, NC",
                "logo_url": None,
            },
            {
                "starts_at": {"day": 1, "month": 12, "year": 2013},
                "ends_at": None,
                "company": "Boone Portraits",
                "company_linkedin_profile_url": None,
                "company_facebook_profile_url": None,
                "title": "Lead Photographer",
                "description": "I photograph families and individuals in a studio setting, walk them through the photos taken to select their favorites, and then sell them packages based on their selections. I then print off those packages within 24 hours for the client to pick up the next day.",
                "location": "Boone, NC",
                "logo_url": None,
            },
            {
                "starts_at": {"day": 1, "month": 1, "year": 2006},
                "ends_at": {"day": 31, "month": 1, "year": 2012},
                "company": "Papa Johns Pizza",
                "company_linkedin_profile_url": None,
                "company_facebook_profile_url": None,
                "title": "Insider / Delivery Driver",
                "description": "Managed dough from arrival in store to preparation and cooking.\n• Assisted customers via telephone and front in both taking new orders and dissatisfactions of current or\nprevious customers.\n• Multi-tasked to prepare dough and pizza, tend ovens, answer phones, and other store tasks regularly.\n• Delivered orders promptly, presenting a courteous and humble drive to each customer at the door.",
                "location": None,
                "logo_url": None,
            },
            {
                "starts_at": {"day": 1, "month": 8, "year": 2010},
                "ends_at": {"day": 30, "month": 4, "year": 2011},
                "company": "Super G Experiential Residency Program",
                "company_linkedin_profile_url": None,
                "company_facebook_profile_url": None,
                "title": "Intern",
                "description": "Attend to needs of residents, document the various events and items made through photo and video, and advertise for events by designing posters and through word of mouth.",
                "location": None,
                "logo_url": None,
            },
            {
                "starts_at": {"day": 1, "month": 6, "year": 2004},
                "ends_at": {"day": 30, "month": 4, "year": 2006},
                "company": "Hungry Howie's Pizza, Inc.",
                "company_linkedin_profile_url": "https://www.linkedin.com/company/hungryhowies",
                "company_facebook_profile_url": None,
                "title": "Insider",
                "description": "Take phone orders, top pizzas, serve as waiter for dining section, manage store interior, prepare toppings for late periods, make and store dough, operate drive-through window",
                "location": None,
                "logo_url": "https://s3.us-west-000.backblazeb2.com/proxycurl/company/hungryhowies/profile?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0004d7f56a0400b0000000001%2F20241031%2Fus-west-000%2Fs3%2Faws4_request&X-Amz-Date=20241031T161641Z&X-Amz-Expires=1800&X-Amz-SignedHeaders=host&X-Amz-Signature=e50c6de8ff30823012372678b65a5c5432c114e8572e719e9900127e7cda18b0",
            },
        ],
        "education": [
            {
                "starts_at": {"day": 1, "month": 1, "year": 2007},
                "ends_at": {"day": 31, "month": 12, "year": 2011},
                "field_of_study": "Design",
                "degree_name": "BFA",
                "school": "University of North Carolina at Greensboro",
                "school_linkedin_profile_url": "https://www.linkedin.com/company/10782/",
                "school_facebook_profile_url": None,
                "description": None,
                "logo_url": "https://s3.us-west-000.backblazeb2.com/proxycurl/company/uncg/profile?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0004d7f56a0400b0000000001%2F20241031%2Fus-west-000%2Fs3%2Faws4_request&X-Amz-Date=20241031T161641Z&X-Amz-Expires=1800&X-Amz-SignedHeaders=host&X-Amz-Signature=5a7f1dc685239111bf9af3d95d3668e891d45c687db00436691b4ac4f06ade5c",
                "grade": None,
                "activities_and_societies": None,
            }
        ],
        "languages": [],
        "languages_and_proficiencies": [],
        "accomplishment_organisations": [],
        "accomplishment_publications": [],
        "accomplishment_honors_awards": [],
        "accomplishment_patents": [],
        "accomplishment_courses": [],
        "accomplishment_projects": [],
        "accomplishment_test_scores": [],
        "volunteer_work": [],
        "certifications": [],
        "connections": 53,
        "people_also_viewed": [
            {
                "link": "https://www.linkedin.com/in/stefanhibl?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAAtiqP8BhpWpLs-8Y2eTM5K72MJenxh97jk",
                "name": "Stefan Hibl",
                "summary": "Photographer Multimedia Specialist at Wright & McGill Co.",
                "location": None,
            },
            {
                "link": "https://www.linkedin.com/in/perparim-qazimi-82230044?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAAlMqJoBG_LgxDy1gnSCicf45dQgmy7lY98",
                "name": "Perparim Qazimi",
                "summary": "Artist & Poet",
                "location": None,
            },
            {
                "link": "https://www.linkedin.com/in/jamesfourniercreativedeveloper?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAAw34EAB-ZURq4I-1QhBGKdI0gOIWghb_v4",
                "name": "James Fournier",
                "summary": "Transforming Ideas into Immersive Experiences | Passionate about Blending Art and Technology",
                "location": None,
            },
            {
                "link": "https://www.linkedin.com/in/imaaronjames?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAAJ5zD4BQNdT2nyB5plIFckVDReo0NPFBPQ",
                "name": "Aaron James",
                "summary": "Sr. Product Designer at Netflix",
                "location": None,
            },
            {
                "link": "https://www.linkedin.com/in/michelle-u-802258b8?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAABj0J4IBUOYh93G_fSp548PRg5HKn1HyTy4",
                "name": "Michelle U.",
                "summary": "Senior Graphic Designer @ Quirch Foods // BFA, Graphic Design ",
                "location": None,
            },
            {
                "link": "https://www.linkedin.com/in/justingarand?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAALE_esBBzAp3ITfTsWJoEBa33JDBV2iUao",
                "name": "Justin Garand",
                "summary": "Independent Creative Director | Freelance Graphic Designer - NBA | WNBA | Ilitch Sports + Entertainment",
                "location": None,
            },
            {
                "link": "https://www.linkedin.com/in/tonyharperereimajretroblack?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAAUmBAcBOkXpoE_UwSuRY26uKqpIR9vGfD4",
                "name": "Ereimaj Retro Black",
                "summary": "Graphic Design",
                "location": None,
            },
            {
                "link": "https://www.linkedin.com/in/jeannie-francis-a950ba61?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAA0B1JEB4ZyORDaZar5nja88Ls_GUu_N_sM",
                "name": "Jeannie Francis",
                "summary": "Executive Assistant Alltech\n& Photographer/Owner Jeannie Francis Pet Pix",
                "location": None,
            },
            {
                "link": "https://www.linkedin.com/in/courtney-hendrickson?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAA88kogBu6lsmfwFbwGvZ9u-wJqdf0VVUsg",
                "name": "Courtney Hendrickson",
                "summary": "Graphic Designer (10+ Years Experience) | Marketing Specialist | UX Enthusiast | Video Editor | Social Media Strategist | Freelance Creative | UGC Creator",
                "location": None,
            },
            {
                "link": "https://www.linkedin.com/in/wesleyshedd?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAANi92UBAzeTWR-DleIf36ers_7gKFdmjPk",
                "name": "Wesley Shedd",
                "summary": "Creative Services Lead, Creative Services at MAPFRE",
                "location": None,
            },
        ],
        "recommendations": [],
        "activities": [],
        "similarly_named_profiles": [],
        "articles": [],
        "groups": [
            {
                "profile_pic_url": "https://media.licdn.com/dms/image/v2/C5607AQFcxp-3PdtwcA/group-logo_image-shrink_400x400/group-logo_image-shrink_400x400/0/1641074363342?e=1730998800&v=beta&t=zjRiczuQPf5Cf0evs535MGYA013O08eIoR99FpbycTg",
                "name": "Web Design",
                "url": "https://www.linkedin.com/groups/123975",
            },
            {
                "profile_pic_url": "https://media.licdn.com/dms/image/v2/C4D07AQE1SqX6tR6ROA/group-logo_image-shrink_48x48/group-logo_image-shrink_48x48/0/1631002600919?e=1730998800&v=beta&t=RFCDTCsRluWzhi3S1etYJT_8h7aQcAO8kPcTS8hjtN0",
                "name": "Adobe Photoshop Group",
                "url": "https://www.linkedin.com/groups/119955",
            },
        ],
        "skills": [],
        "inferred_salary": None,
        "gender": None,
        "birth_date": None,
        "industry": None,
        "extra": None,
        "interests": [],
        "personal_emails": [],
        "personal_numbers": [],
    }
